# cache-bust: 2026-03-19-03

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["echo 'build complete'"]

[start]
cmd = "pnpm --filter @zapsight/queue run start"
